### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/deploy2020#10]
https://www.portainer.io/

Ist aber für mich momentan out of scope, weil nie genauer abgesprochen

**Comment by dbrgn** [comment]
Habe jetzt Watchtower mal eingerichtet: aa57fb337ee4f8f222a023a986b59d1fd6f50551

Musste dafür noch eine Änderung im docker-compose File machen:

https://github.com/studentenportal/web/pull/259

Scheint zu klappen:

```
time="2020-07-29T21:34:32Z" level=info msg="Found new studentenportal/web:latest image (sha256:0019d849ba93c808efbb5de00596843724b200c63aebc56e7ba54445641e14e3)"
time="2020-07-29T21:34:34Z" level=info msg="Stopping /web_studentenportal_1 (d6bd1e24075db7535dfc8102e2432d9ab38994cd35d350488ba60482defc0e81) with SIGTERM"
time="2020-07-29T21:34:45Z" level=info msg="Creating /web_studentenportal_1"
time="2020-07-29T21:34:46Z" level=info msg="Removing image sha256:558d6db1ce37934c3b04966b5d8e240d7f3ab8414f3db9ac63bcc69372b4892f"
```

:tada: 

Der Nginx-Container wird momentan noch nicht updated, da wir davon keine Images builden / publizieren. Sollte man wohl in einem nächsten Schritt noch tun.

Aber für den Moment gilt: Nach einem Push auf den master-Branch wird nach der Publikation des Docker-Images innerhalb einer Minute der Web-Container re-deployed.

@fabianhauser @The-Compiler können wir dieses Issue schliessen?

**Comment by dbrgn** [comment]
(Watchtower könnte man übrigens auch per HTTP triggern. Aber ich denke Polling ist schöner, da komplett entkoppelt.)

**Comment by The-Compiler** [comment]
Sehr cool, ich hab mir das irgendwie deutlich komplizierter vorgestellt! Ja, ich denke wir können das Issue zumachen. Eine Minute delay ist wohl kein Problem und das Ansible auto-deployment brauchts IMHO nicht umbedingt (Änderungen wirds wohl eher an der Codebase selbst geben).
