### ISSUE TITLE
PermissionError beim Hochladen von Dokumenten

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/deploy2020#23]
In unserer Mailbox sind einige internal server errors aus dem Juni/Juli, die ca. so aussehen:

```
Exception Type: PermissionError at /dokumente/mste/add/
Exception Value: [Errno 13] Permission denied: '/srv/www/studentenportal/media/documents/mste/2020-07-02_16-01-36.docx'
Request information:
USER: ******
```

Da scheint noch irgendwas kaputt zu sein - @dbrgn @fabianhauser hat das jemand von euch schon angeschaut?

**Comment by fabianhauser** [comment]
Nein, bin bisher noch nicht dazu gekommen...

**Comment by The-Compiler** [comment]
Hab jetzt grad nochmals getestet, scheint (sowohl vor als auch nach dem Anpassen der Berechtigungen) zu funktionieren.
